In [2]:
import torch
import numpy as np

# **List**


In [3]:
my_list = [[1,2,3,4,5],[6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [7]:
np1 = np.random.rand(3,4) 
np1 

array([[0.23557047, 0.43411203, 0.55148525, 0.50346697],
       [0.60879781, 0.49395619, 0.75900037, 0.58463607],
       [0.19953838, 0.5510452 , 0.7162173 , 0.34940085]])

In [8]:
np1.dtype

dtype('float64')

In [10]:
tensor_2d=torch.randn(3,4)
tensor_2d

tensor([[ 0.3275,  0.5370, -0.1713, -0.0882],
        [ 0.1161, -1.9012,  1.0726,  2.9289],
        [ 1.4880,  2.2395, -0.6284,  0.3280]])

In [12]:
tensor_3d=torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [13]:
##create tensor outof numpy array
my_tensor= torch.tensor(np1)
my_tensor

tensor([[0.2356, 0.4341, 0.5515, 0.5035],
        [0.6088, 0.4940, 0.7590, 0.5846],
        [0.1995, 0.5510, 0.7162, 0.3494]], dtype=torch.float64)